optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005, 
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { _base_: configs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'train'}},
  val : { _base_: configs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'test'}},
  test : { _base_: configs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'test'}}}
model : {
  NAME: PointMamba,
  trans_dim: 384, 
  depth: 2, 
  drop_path_rate: 0.1, 
  cls_dim: 40, 
  num_heads: 6,
  group_size: 32, 
  num_group: 256, 
  encoder_dims: 256,

  use_llama: False,
  only_mlp: False,
  use_vgg: False,
}
npoints: 4096
total_bs : 32
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10


consider_metric: CDL1