optimizer : {
  type: AdamW,
  kwargs: {
  lr : 0.0005, 
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs : 10
}}

dataset : {
  train : { _base_: configs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'train'}},
  val : { _base_: configs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'test'}},
  test : { _base_: configs/dataset_configs/ModelNet40.yaml, 
            others: {subset: 'test'}}}
model : {
  NAME: PointTransformer,
  trans_dim: 384, 
  depth: 12, 
  drop_path_rate: 0.1, 
  cls_dim: 40, 
  num_heads: 6,
  group_size: 32, 
  num_group: 512, 
  encoder_dims: 256,

  use_llama: False,
  
  only_mlp: True,
  only_mlp_cfg: {
    only_mlp_n: 4,
    only_mlp_l0: {"dim_in": 384, "dim_out": 4096},
    only_mlp_l1: {"dim_in": 4096, "dim_out": 4096},
    only_mlp_l2: {"dim_in": 4096, "dim_out": 4096},
    only_mlp_l3: {"dim_in": 4096, "dim_out": 384}
  },
}
npoints: 8192
total_bs : 32
step_per_update : 1
max_epoch : 300
grad_norm_clip : 10


consider_metric: CDL1